# Generated by Django 5.2.5 on 2025-08-17 19:32

import django.db.models.deletion
import games.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperAndPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('is_dev', models.BooleanField()),
                ('is_pub', models.BooleanField()),
                ('opened_at', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=4096, validators=[games.validators.LengthRangeValidator(100, 2000)])),
                ('rating', models.FloatField(validators=[games.validators.MinMaxValidator(0, 10)])),
                ('cover', models.ImageField(upload_to='%Y/%m/cover')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='%Y/%m/banner')),
                ('release_date', models.DateField()),
                ('version', models.CharField(blank=True, default='1.0.0', max_length=15)),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_games', to='games.developerandpublisher')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_games', to='games.developerandpublisher')),
                ('genres', models.ManyToManyField(related_name='games', to='games.genre')),
            ],
        ),
    ]
