# Generated by Django 5.2.5 on 2025-08-17 20:40

import django.db.models.deletion
import games.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_developerandpublisher_is_dev_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[games.validators.MinMaxValidator(0, 10)])),
                ('recommend', models.BooleanField(default=True)),
                ('text', models.TextField(validators=[games.validators.LengthRangeValidator(20, 2000)])),
                ('status', models.PositiveIntegerField(choices=[(0, 'Planning to play'), (1, 'Playing'), (2, 'Finished main game'), (3, 'Completed'), (4, 'Dropped')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_reviews', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.game')),
            ],
        ),
    ]
