# Generated by Django 5.2.5 on 2025-08-19 14:44

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='gameplay_duration',
            field=models.FloatField(default=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='monthly_views',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='total_views',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='publisher',
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(related_name='supporteded_games', to='games.platform'),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='platforms',
            field=models.ManyToManyField(related_name='related_reviews', to='games.platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ManyToManyField(related_name='published_games', to='games.developerandpublisher'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ManyToManyField(related_name='released_games', to='games.developerandpublisher'),
        ),
    ]
