# Generated by Django 5.2.5 on 2025-08-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_platform_game_gameplay_duration_game_monthly_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='company',
            field=models.ManyToManyField(related_name='released_consoles', to='games.developerandpublisher'),
        ),
    ]
