# Generated by Django 5.2.5 on 2025-08-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_platform_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='weekly_views',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
