# Generated by Django 5.2.5 on 2025-08-19 15:03

import games.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_weekly_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user_rating',
            field=models.FloatField(default=10, validators=[games.validators.MinMaxValidator(0, 10)]),
            preserve_default=False,
        ),
    ]
